### ISSUE TITLE
Use of Dosis Font

### ISSUE THREAD

**Issue by josuebasurto** [elartix/dosis-fontface#1]
Question: 
Good day, we're using dosis font in and Android app:
Are you owner?
Where can I find License?
Android app is non-profit.

Regards.

**Comment by elartix** [comment]
Sorry fo delay.

As far as I know Dosis font is free with [SIL Open Font License, 1.1](http://scripts.sil.org/OFL)

[https://www.google.com/fonts/specimen/Dosis](https://www.google.com/fonts/specimen/Dosis)
